import Link from "next/link";

export default function TermsPage() {
  return (
    <div className="card max-w-3xl mx-auto mt-8">
      <h1 className="text-2xl font-bold text-navy mb-2">Terms and Conditions — CMMC Audit Helper</h1>
      <p className="text-sm text-gray-500 mb-6"><strong>Last updated: 23 July 2026</strong></p>

      <p className="mb-4">Please read these Terms and Conditions (&quot;Terms&quot;) carefully before using CMMC Audit Helper (the &quot;Service&quot;), operated as a sole trader (&quot;we&quot;, &quot;us&quot;, &quot;our&quot;). By creating an account or using the Service, you agree to these Terms.</p>

      <h2 className="text-lg font-bold text-navy mt-6 mb-2">1. What the Service Is</h2>
      <p className="mb-4">CMMC Audit Helper is a self-assessment preparation tool for organisations working toward Cybersecurity Maturity Model Certification (CMMC) Level 1 or Level 2 compliance. It helps you organise control responses, evidence, and Plan of Action &amp; Milestones (POA&amp;M) items, and generates draft documentation (including a summary System Security Plan and POA&amp;M) for your own use.</p>
      <p className="mb-4"><strong>The Service is not a certification, does not constitute legal, compliance, or cybersecurity advice, and does not replace a Certified Third-Party Assessment Organization (C3PAO) assessment.</strong> You are solely responsible for the accuracy of any information you submit to the Department of Defense, the Supplier Performance Risk System (SPRS), or any other government body. Submitting false or inaccurate compliance claims may result in liability under the False Claims Act or other applicable law. We accept no responsibility for the consequences of any submission you make using output generated by the Service.</p>

      <h2 className="text-lg font-bold text-navy mt-6 mb-2">2. Eligibility</h2>
      <p className="mb-4">The Service is intended for use by businesses and individuals acting in a business capacity. You must have the authority to enter into these Terms on behalf of your organisation, where applicable.</p>
      <p className="mb-4"><strong>Notice regarding the operator:</strong> This Service is operated by an individual sole trader who is a minor (under 18) under the laws of England and Wales. Under English law, contracts entered into with a minor may be voidable at the minor&apos;s option in certain circumstances, and this may affect the enforceability of these Terms, including the payment and refund provisions below. We disclose this so you can make an informed decision about whether to purchase; if this is a concern for your organisation&apos;s procurement or legal requirements, please contact us before purchasing.</p>

      <h2 className="text-lg font-bold text-navy mt-6 mb-2">3. Payment and Refunds</h2>
      <ul className="list-disc pl-5 space-y-2 mb-4 text-sm">
        <li>The Service is offered on a one-time payment basis (currently £1,000 per assessment package), processed via Stripe.</li>
        <li>You may use the assessment tool, including entering control responses and uploading evidence, free of charge. Payment is required only to generate and download the final compliance package (SSP, POA&amp;M, and evidence bundle).</li>
        <li><strong>All payments are non-refundable once the package has been generated and downloaded.</strong> We do not guarantee refunds for any reason after export, including dissatisfaction with the output, changes to CMMC requirements, or issues arising from information you provided.</li>
        <li>Notwithstanding the above, we may at our sole discretion offer a refund, credit, or fix in the case of a genuine technical fault with the Service. This is offered as a goodwill gesture and does not create any ongoing entitlement or precedent for future purchases.</li>
      </ul>

      <h2 className="text-lg font-bold text-navy mt-6 mb-2">4. Your Responsibilities</h2>
      <p className="mb-4">You are responsible for:</p>
      <ul className="list-disc pl-5 space-y-1 mb-4 text-sm">
        <li>The accuracy and completeness of the information and evidence you enter into the Service</li>
        <li>Verifying that any generated documentation reflects your organisation&apos;s actual security posture before relying on it or submitting it anywhere</li>
        <li>Maintaining the confidentiality of your account credentials</li>
        <li>Complying with all applicable laws, including in connection with any DoD contract or subcontract</li>
      </ul>

      <h2 className="text-lg font-bold text-navy mt-6 mb-2">5. Intellectual Property</h2>
      <p className="mb-4">The Service, its underlying software, control content, and design are owned by us. You retain ownership of the data, evidence files, and content you upload. We do not claim ownership of your compliance data.</p>

      <h2 className="text-lg font-bold text-navy mt-6 mb-2">6. Disclaimers and Limitation of Liability</h2>
      <p className="mb-4">The Service is provided &quot;as is&quot; without warranties of any kind, express or implied, including fitness for a particular purpose or accuracy of generated content.</p>
      <p className="mb-4">To the maximum extent permitted by law, we are not liable for any indirect, incidental, or consequential losses, including lost contracts, lost profits, or regulatory penalties, arising from your use of the Service or reliance on any documentation it generates. Our total liability to you for any claim arising from the Service is limited to the amount you paid us in the 12 months preceding the claim.</p>
      <p className="mb-4">Nothing in these Terms excludes or limits liability that cannot be excluded or limited under applicable law.</p>

      <h2 className="text-lg font-bold text-navy mt-6 mb-2">7. Data and Evidence Files</h2>
      <p className="mb-4">Your evidence files and assessment data are stored securely and are used only to provide the Service to you. See our Privacy Policy for full details on data handling.</p>

      <h2 className="text-lg font-bold text-navy mt-6 mb-2">8. Termination</h2>
      <p className="mb-4">We may suspend or terminate your account if you breach these Terms or misuse the Service. You may stop using the Service at any time.</p>

      <h2 className="text-lg font-bold text-navy mt-6 mb-2">9. Changes to These Terms</h2>
      <p className="mb-4">We may update these Terms from time to time. Continued use of the Service after an update constitutes acceptance of the revised Terms. Material changes will be noted with an updated &quot;Last updated&quot; date above.</p>

      <h2 className="text-lg font-bold text-navy mt-6 mb-2">10. Governing Law</h2>
      <p className="mb-4">These Terms are governed by the laws of England and Wales, without regard to conflict of law principles.</p>

      <h2 className="text-lg font-bold text-navy mt-6 mb-2">11. Contact</h2>
      <p className="mb-4">Questions about these Terms can be sent via the contact details provided on the Service.</p>
    </div>
  );
}
