import { Control, CMMCLevel } from "./types";

export const LEVEL1_CONTROLS: Control[] = [
  {
    id: "L1-01",
    control_id: "FAR 52.204-21(a)",
    domain: "Access Control",
    question: "Do you limit who can access your systems to only people who need it?",
    good: "You have a list of who has access to each system. When someone leaves or changes roles, you remove or update their access.",
    mistake: 'Shared folders open to "Everyone." Old employee accounts still active. Vendor accounts that never expire.',
    evidence_required: true,
    evidence_guidance: "User access list, screenshot of permissions settings, HR/IT process for adding/removing users.",
  },
  {
    id: "L1-02",
    control_id: "FAR 52.204-21(b)",
    domain: "Access Control",
    question: "Do you limit the types of transactions and functions that users can perform?",
    good: "Users have only the permissions they need to do their job—not full admin rights unless required.",
    mistake: "Everyone has administrative or full write access to all files and systems.",
    evidence_required: true,
    evidence_guidance: "User role definitions, permission matrices, screenshots of user privilege settings.",
  },
  {
    id: "L1-03",
    control_id: "FAR 52.204-21(c)",
    domain: "Awareness & Training",
    question: "Do you train your employees on basic cybersecurity practices?",
    good: "All employees receive annual security awareness training covering phishing, passwords, and handling of sensitive information.",
    mistake: 'No formal training program; employees learn "on the job" with no documented guidance.',
    evidence_required: true,
    evidence_guidance: "Training records, slide decks, completion certificates, sign-in sheets.",
  },
  {
    id: "L1-04",
    control_id: "FAR 52.204-21(d)",
    domain: "Audit & Accountability",
    question: "Do you keep logs of who accesses your systems and what they do?",
    good: "You have audit logs enabled that track user logins, file access, and system changes.",
    mistake: "Logging is disabled or logs are never reviewed.",
    evidence_required: true,
    evidence_guidance: "Screenshots of audit log settings, sample log entries, log retention policy.",
  },
  {
    id: "L1-05",
    control_id: "FAR 52.204-21(e)",
    domain: "Configuration Management",
    question: "Do you have a process for securely configuring your systems?",
    good: "You follow a secure configuration baseline (e.g., CIS benchmarks) for operating systems and applications.",
    mistake: "Systems are deployed with default passwords and unnecessary services enabled.",
    evidence_required: true,
    evidence_guidance: "Configuration checklists, screenshots of system settings, baseline documentation.",
  },
  {
    id: "L1-06",
    control_id: "FAR 52.204-21(f)",
    domain: "Identification & Authentication",
    question: "Do you require unique IDs and strong passwords for each user?",
    good: "Each user has a unique username and password. Passwords meet complexity requirements (length, character types).",
    mistake: 'Shared accounts, weak passwords like "password123," no password expiration.',
    evidence_required: true,
    evidence_guidance: "Password policy document, screenshots of login settings, user account list.",
  },
  {
    id: "L1-07",
    control_id: "FAR 52.204-21(g)",
    domain: "Incident Response",
    question: "Do you have a plan for responding to security incidents?",
    good: "You have a documented incident response plan that includes who to contact and what steps to take.",
    mistake: "No plan; employees don't know who to call if a breach occurs.",
    evidence_required: true,
    evidence_guidance: "Incident response plan document, contact list, incident reporting form.",
  },
  {
    id: "L1-08",
    control_id: "FAR 52.204-21(h)",
    domain: "Maintenance",
    question: "Do you regularly maintain and patch your systems?",
    good: "You have a schedule for applying security patches and updates to all systems within a reasonable timeframe.",
    mistake: "Patches are applied inconsistently or not at all. Systems are running outdated software.",
    evidence_required: true,
    evidence_guidance: "Patch management policy, maintenance logs, screenshots of update settings.",
  },
  {
    id: "L1-09",
    control_id: "FAR 52.204-21(i)",
    domain: "Media Protection",
    question: "Do you securely dispose of or sanitize media when it's no longer needed?",
    good: "You have a process for wiping or destroying hard drives, USB drives, and paper documents before disposal.",
    mistake: "Old hard drives and documents are thrown in the trash without sanitization.",
    evidence_required: true,
    evidence_guidance: "Media disposal policy, destruction logs, photos of shredded media.",
  },
  {
    id: "L1-10",
    control_id: "FAR 52.204-21(j)",
    domain: "Personnel Security",
    question: "Do you screen employees before giving them access to sensitive information?",
    good: "You conduct background checks and verify employment history before granting system access.",
    mistake: "No screening process; anyone can get access regardless of background.",
    evidence_required: true,
    evidence_guidance: "Background check policy, signed acknowledgments, HR screening records.",
  },
  {
    id: "L1-11",
    control_id: "FAR 52.204-21(k)",
    domain: "Physical Protection",
    question: "Do you limit physical access to systems and sensitive areas?",
    good: "You have locks, access cards, or other controls that restrict physical entry to server rooms and offices.",
    mistake: "Server rooms are unlocked; anyone can walk in and access equipment.",
    evidence_required: true,
    evidence_guidance: "Physical security policy, access logs, photos of access controls.",
  },
  {
    id: "L1-12",
    control_id: "FAR 52.204-21(l)",
    domain: "Risk Assessment",
    question: "Do you conduct regular risk assessments to identify vulnerabilities?",
    good: "You perform a formal risk assessment at least annually to identify and prioritize security risks.",
    mistake: "No risk assessments performed; vulnerabilities are unknown.",
    evidence_required: true,
    evidence_guidance: "Risk assessment reports, vulnerability scan results, risk register.",
  },
  {
    id: "L1-13",
    control_id: "FAR 52.204-21(m)",
    domain: "Security Assessment",
    question: "Do you test your security controls to verify they're working?",
    good: "You conduct periodic security testing (e.g., vulnerability scans, penetration tests) to validate controls.",
    mistake: "No testing is done; you assume controls are working without verification.",
    evidence_required: true,
    evidence_guidance: "Test reports, scan results, remediation tracking.",
  },
  {
    id: "L1-14",
    control_id: "FAR 52.204-21(n)",
    domain: "System & Communications Protection",
    question: "Do you protect your systems and communications from unauthorized access?",
    good: "You use firewalls, encryption, and other controls to protect data in transit and at rest.",
    mistake: "No encryption for sensitive data; firewalls are disabled or misconfigured.",
    evidence_required: true,
    evidence_guidance: "Firewall rules, encryption policy, screenshots of security settings.",
  },
  {
    id: "L1-15",
    control_id: "FAR 52.204-21(o)",
    domain: "System & Information Integrity",
    question: "Do you have controls to protect against malicious code (viruses, ransomware)?",
    good: "You use antivirus/antimalware software with regular updates and scans on all systems.",
    mistake: "No antivirus software or it's outdated. Users can download and install anything.",
    evidence_required: true,
    evidence_guidance: "Antivirus policy, scan logs, screenshots of protection settings.",
  },
];

export const LEVEL2_CONTROLS: Control[] = [
  // ── Access Control (AC) ── 22 controls
  { id: "L2-001", control_id: "NIST.AC.001", domain: "Access Control", question: "Limit information system access to authorized users.", good: "Access is restricted based on job role and need-to-know. Reviews are conducted periodically.", mistake: "Access is granted broadly without justification. No regular access reviews.", evidence_required: true, evidence_guidance: "User access review logs, permission matrices, HR termination records." },
  { id: "L2-002", control_id: "NIST.AC.002", domain: "Access Control", question: "Limit information system access to authorized processes.", good: "Only approved processes and service accounts can access systems and data.", mistake: "Unapproved scripts or services running with elevated privileges.", evidence_required: true, evidence_guidance: "Service account inventory, process whitelist, task scheduler screenshots." },
  { id: "L2-003", control_id: "NIST.AC.003", domain: "Access Control", question: "Control the flow of CUI in accordance with approved authorizations.", good: "Data flow is documented and controlled. CUI does not leak to unauthorized systems or networks.", mistake: "CUI is emailed to personal accounts or stored in unapproved cloud services.", evidence_required: true, evidence_guidance: "Data flow diagrams, DLP policy, network segmentation documentation." },
  { id: "L2-004", control_id: "NIST.AC.004", domain: "Access Control", question: "Separate the duties of individuals to reduce risk of malicious activity.", good: "Critical tasks require two or more individuals. No single person has end-to-end control.", mistake: "One person can approve, process, and audit sensitive transactions without oversight.", evidence_required: true, evidence_guidance: "Separation of duties matrix, role definitions, approval workflows." },
  { id: "L2-005", control_id: "NIST.AC.005", domain: "Access Control", question: "Employ the principle of least privilege for all system accounts.", good: "Users and processes have only the minimum permissions needed to perform their function.", mistake: "Default admin rights granted to all users. Service accounts have domain admin.", evidence_required: true, evidence_guidance: "Privilege audit reports, role-based access control configuration." },
  { id: "L2-006", control_id: "NIST.AC.006", domain: "Access Control", question: "Use non-privileged accounts for non-administrative functions.", good: "Admins use standard user accounts for daily tasks and only elevate when necessary.", mistake: "IT staff logged in as domain admin all day for email and browsing.", evidence_required: true, evidence_guidance: "Account usage policy, screenshots showing separate admin/standard accounts." },
  { id: "L2-007", control_id: "NIST.AC.007", domain: "Access Control", question: "Prevent non-privileged users from executing privileged functions.", good: "Privileged functions require explicit elevation and are logged.", mistake: "Standard users can install software or modify system settings.", evidence_required: true, evidence_guidance: "UAC/GPO settings, privilege escalation logs." },
  { id: "L2-008", control_id: "NIST.AC.008", domain: "Access Control", question: "Limit unsuccessful logon attempts.", good: "Accounts lock after a defined number of failed login attempts (e.g., 5 attempts).", mistake: "Unlimited login attempts allow brute-force password attacks.", evidence_required: true, evidence_guidance: "Account lockout policy settings, screenshots of security policy configuration." },
  { id: "L2-009", control_id: "NIST.AC.009", domain: "Access Control", question: "Provide a warning banner that informs users of security policies.", good: "A login banner is displayed informing users of monitoring and acceptable use.", mistake: "No login banner; users are unaware systems are monitored.", evidence_required: true, evidence_guidance: "Screenshot of login banner, GPO or registry settings for legal notice." },
  { id: "L2-010", control_id: "NIST.AC.010", domain: "Access Control", question: "Enforce session termination after a defined period of inactivity.", good: "Sessions automatically lock or log out after 15 minutes of inactivity.", mistake: "Sessions remain unlocked indefinitely. Users walk away leaving systems accessible.", evidence_required: true, evidence_guidance: "Screensaver/screen lock policy, session timeout configuration." },
  { id: "L2-011", control_id: "NIST.AC.011", domain: "Access Control", question: "Monitor and control remote access sessions.", good: "Remote access is logged, time-limited, and monitored for unusual activity.", mistake: "Unrestricted remote access with no logging or session controls.", evidence_required: true, evidence_guidance: "VPN/RDP logs, remote access policy, session monitoring configuration." },
  { id: "L2-012", control_id: "NIST.AC.012", domain: "Access Control", question: "Employ cryptographic mechanisms to protect remote access.", good: "Remote connections use encryption (VPN, TLS) to protect data in transit.", mistake: "Remote desktop exposed directly to internet without VPN or encryption.", evidence_required: true, evidence_guidance: "VPN configuration, TLS certificate, encrypted protocol settings." },
  { id: "L2-013", control_id: "NIST.AC.013", domain: "Access Control", question: "Route remote access through authorized access points.", good: "All remote access goes through managed VPN concentrators or secure gateways.", mistake: "Users connect from anywhere through unmanaged ports or personal devices.", evidence_required: true, evidence_guidance: "Network topology diagram, firewall rules for remote access." },
  { id: "L2-014", control_id: "NIST.AC.014", domain: "Access Control", question: "Authorize and document remote access to systems.", good: "Remote access is formally approved, documented, and periodically reviewed.", mistake: "No approval process; remote access is ad-hoc with no documentation.", evidence_required: true, evidence_guidance: "Remote access authorization forms, approved access list." },
  { id: "L2-015", control_id: "NIST.AC.015", domain: "Access Control", question: "Control wireless network access.", good: "Wireless networks require authentication and encryption (WPA3/WPA2-Enterprise).", mistake: "Open Wi-Fi network or shared PSK with no user accountability.", evidence_required: true, evidence_guidance: "Wireless controller configuration, RADIUS/802.1X settings." },
  { id: "L2-016", control_id: "NIST.AC.016", domain: "Access Control", question: "Protect wireless access using authentication and encryption.", good: "Enterprise authentication (802.1X) is used with strong encryption.", mistake: "WEP or open networks used. Weak shared passwords for Wi-Fi.", evidence_required: true, evidence_guidance: "Wireless security policy, encryption settings screenshot." },
  { id: "L2-017", control_id: "NIST.AC.017", domain: "Access Control", question: "Control access to systems and applications from external networks.", good: "External access is restricted by firewall rules, IP whitelisting, or VPN requirements.", mistake: "Internal applications exposed to the public internet without access controls.", evidence_required: true, evidence_guidance: "Firewall rule set, external access review, application gateway configuration." },
  { id: "L2-018", control_id: "NIST.AC.018", domain: "Access Control", question: "Restrict access to dangerous functions and programs.", good: "Use of dangerous functions (e.g., cmd, PowerShell) is restricted and logged.", mistake: "All users can run PowerShell scripts or command prompt without restriction.", evidence_required: true, evidence_guidance: "AppLocker/SRP rules, PowerShell constrained language mode settings." },
  { id: "L2-019", control_id: "NIST.AC.019", domain: "Access Control", question: "Limit access to security tools and sensitive data.", good: "Only security personnel have access to security tools (SIEM, vulnerability scanners).", mistake: "Any user can access and modify security tool configurations.", evidence_required: true, evidence_guidance: "Security tool access list, audit log of security tool usage." },
  { id: "L2-020", control_id: "NIST.AC.020", domain: "Access Control", question: "Control access to audit logs and system records.", good: "Audit logs are protected from modification and only accessible to authorized staff.", mistake: "Logs are writable by anyone or stored in unsecured locations.", evidence_required: true, evidence_guidance: "Log access permissions, immutable log configuration." },
  { id: "L2-021", control_id: "NIST.AC.021", domain: "Access Control", question: "Manage privileged access to system resources.", good: "Privileged accounts are tracked, reviewed quarterly, and have strong authentication.", mistake: "Shared root/admin passwords. No review of privileged access.", evidence_required: true, evidence_guidance: "Privileged access management (PAM) tool, privileged account review logs." },
  { id: "L2-022", control_id: "NIST.AC.022", domain: "Access Control", question: "Implement automated mechanisms to manage access controls.", good: "Access controls are enforced through automation (AD groups, IAM policies) not manual processes.", mistake: "Access management relies on manual processes without automation.", evidence_required: true, evidence_guidance: "AD/IAM configuration, automated provisioning/deprovisioning workflows." },

  // ── Awareness & Training (AT) ── 3 controls
  { id: "L2-023", control_id: "NIST.AT.001", domain: "Awareness & Training", question: "Provide security awareness training to all employees.", good: "Training is documented, tracked, and completed annually with refreshers.", mistake: "Training is informal or skipped entirely.", evidence_required: true, evidence_guidance: "Training completion records, training materials, LMS reports." },
  { id: "L2-024", control_id: "NIST.AT.002", domain: "Awareness & Training", question: "Provide specialized training for users with privileged access.", good: "Privileged users receive role-specific training on secure administration practices.", mistake: "All users get the same generic training regardless of role.", evidence_required: true, evidence_guidance: "Role-based training matrix, privileged user training certificates." },
  { id: "L2-025", control_id: "NIST.AT.003", domain: "Awareness & Training", question: "Provide training on recognizing and reporting social engineering attacks.", good: "Employees receive phishing awareness training and regular simulated phishing tests.", mistake: "No social engineering awareness program. Employees fall for phishing.", evidence_required: true, evidence_guidance: "Phishing simulation results, social engineering training records." },

  // ── Audit & Accountability (AU) ── 9 controls
  { id: "L2-026", control_id: "NIST.AU.001", domain: "Audit & Accountability", question: "Generate audit records for system events and user activity.", good: "Audit logging is enabled and logs are reviewed regularly. Retention policies are documented.", mistake: "Logging is disabled or logs are never reviewed.", evidence_required: true, evidence_guidance: "Audit policy configuration, sample log entries, log review schedule." },
  { id: "L2-027", control_id: "NIST.AU.002", domain: "Audit & Accountability", question: "Ensure audit records contain sufficient detail to identify events.", good: "Logs capture user ID, timestamp, source IP, event type, and outcome.", mistake: "Logs are vague or missing key details needed for investigation.", evidence_required: true, evidence_guidance: "Sample log format, audit configuration showing fields captured." },
  { id: "L2-028", control_id: "NIST.AU.003", domain: "Audit & Accountability", question: "Protect audit records from unauthorized access, modification, and deletion.", good: "Audit logs are stored on a separate system with write-once/read-many protections.", mistake: "Logs stored on the same system being monitored; easily deleted by attackers.", evidence_required: true, evidence_guidance: "Log server configuration, SIEM access controls, immutable storage settings." },
  { id: "L2-029", control_id: "NIST.AU.004", domain: "Audit & Accountability", question: "Retain audit records for the required retention period.", good: "Logs are retained per policy (typically 1+ years) with a documented retention schedule.", mistake: "Logs are deleted after a few days due to disk space constraints.", evidence_required: true, evidence_guidance: "Log retention policy, archived log storage configuration." },
  { id: "L2-030", control_id: "NIST.AU.005", domain: "Audit & Accountability", question: "Monitor and review audit logs for anomalies and suspicious activity.", good: "Logs are actively reviewed with automated alerting for suspicious patterns.", mistake: "Logs are collected but never reviewed; no alerting configured.", evidence_required: true, evidence_guidance: "SIEM dashboard, log review reports, alert configuration." },
  { id: "L2-031", control_id: "NIST.AU.006", domain: "Audit & Accountability", question: "Alert on critical security events and anomalies.", good: "Automated alerts notify security staff of critical events in real time.", mistake: "Security events go unnoticed until days or weeks later.", evidence_required: true, evidence_guidance: "Alert rules configuration, alert notification history." },
  { id: "L2-032", control_id: "NIST.AU.007", domain: "Audit & Accountability", question: "Use automated tools to analyze and correlate audit data.", good: "SIEM or correlation tools aggregate and analyze logs from multiple sources.", mistake: "Logs are manually reviewed in isolation with no correlation.", evidence_required: true, evidence_guidance: "SIEM/correlation engine configuration, correlation rules." },
  { id: "L2-033", control_id: "NIST.AU.008", domain: "Audit & Accountability", question: "Protect audit tools from unauthorized access.", good: "Only authorized security personnel can access and configure audit tools.", mistake: "Any administrator can disable logging or modify audit settings.", evidence_required: true, evidence_guidance: "Audit tool access control list, change management for audit settings." },
  { id: "L2-034", control_id: "NIST.AU.009", domain: "Audit & Accountability", question: "Centralize audit record management and analysis.", good: "Logs from all systems are collected in a centralized location for unified analysis.", mistake: "Logs scattered across individual systems with no central collection.", evidence_required: true, evidence_guidance: "Central log collection architecture diagram, log aggregator configuration." },

  // ── Configuration Management (CM) ── 7 controls
  { id: "L2-035", control_id: "NIST.CM.001", domain: "Configuration Management", question: "Establish and maintain baseline configurations for systems.", good: "Configuration baselines are documented and changes follow a formal process.", mistake: "Configurations are ad-hoc with no baseline or change control.", evidence_required: true, evidence_guidance: "Baseline configuration documents, system build checklist." },
  { id: "L2-036", control_id: "NIST.CM.002", domain: "Configuration Management", question: "Control and manage changes to system configurations.", good: "All configuration changes go through a formal change management process with approval.", mistake: "Changes are made ad-hoc with no documentation or approval.", evidence_required: true, evidence_guidance: "Change request forms, change approval records, CAB minutes." },
  { id: "L2-037", control_id: "NIST.CM.003", domain: "Configuration Management", question: "Deploy system updates and patches in a timely manner.", good: "Patches are tested and deployed within a defined timeframe based on severity.", mistake: "Patches are applied inconsistently or not at all.", evidence_required: true, evidence_guidance: "Patch management policy, patch deployment reports, vulnerability scan results." },
  { id: "L2-038", control_id: "NIST.CM.004", domain: "Configuration Management", question: "Maintain and monitor configuration settings for security.", good: "Configuration compliance is continuously monitored and deviations are flagged.", mistake: "No ongoing monitoring of configuration compliance.", evidence_required: true, evidence_guidance: "Configuration compliance scan results, drift detection reports." },
  { id: "L2-039", control_id: "NIST.CM.005", domain: "Configuration Management", question: "Restrict use of unnecessary functions, ports, and services.", good: "Only necessary ports, protocols, and services are enabled. Unnecessary ones are disabled.", mistake: "Default services and ports are all enabled with no hardening.", evidence_required: true, evidence_guidance: "Port scan results, service inventory, system hardening checklist." },
  { id: "L2-040", control_id: "NIST.CM.006", domain: "Configuration Management", question: "Use automated mechanisms to enforce and monitor configurations.", good: "Group Policy, DSC, or configuration management tools enforce settings automatically.", mistake: "Configurations are maintained manually with no enforcement.", evidence_required: true, evidence_guidance: "GPO/DSC configuration, configuration management tool settings." },
  { id: "L2-041", control_id: "NIST.CM.007", domain: "Configuration Management", question: "Develop and maintain configuration management policies.", good: "Formal CM policy exists and is reviewed annually.", mistake: "No CM policy or plan exists.", evidence_required: true, evidence_guidance: "Configuration management policy document, policy review records." },

  // ── Identification & Authentication (IA) ── 11 controls
  { id: "L2-042", control_id: "NIST.IA.001", domain: "Identification & Authentication", question: "Identify and authenticate users before granting access.", good: "All users have unique credentials. MFA is enforced where possible.", mistake: "Shared accounts, weak passwords, no MFA.", evidence_required: true, evidence_guidance: "Authentication policy, MFA enrollment reports." },
  { id: "L2-043", control_id: "NIST.IA.002", domain: "Identification & Authentication", question: "Authenticate users using at least two factors of authentication.", good: "MFA is enforced for all remote access and privileged accounts.", mistake: "Single-factor authentication only. No MFA anywhere.", evidence_required: true, evidence_guidance: "MFA configuration settings, MFA enrollment records." },
  { id: "L2-044", control_id: "NIST.IA.003", domain: "Identification & Authentication", question: "Use multifactor authentication for network access.", good: "Network access (VPN, Wi-Fi) requires MFA.", mistake: "Network access uses password only.", evidence_required: true, evidence_guidance: "VPN MFA configuration, RADIUS with MFA settings." },
  { id: "L2-045", control_id: "NIST.IA.004", domain: "Identification & Authentication", question: "Employ replay-resistant authentication mechanisms.", good: "Authentication protocols include nonces, timestamps, or challenges to prevent replay.", mistake: "Basic authentication without replay protection.", evidence_required: true, evidence_guidance: "Kerberos/NTLMv2 settings, authentication protocol documentation." },
  { id: "L2-046", control_id: "NIST.IA.005", domain: "Identification & Authentication", question: "Protect authenticator information from unauthorized disclosure.", good: "Password hashes are salted and stored securely. No plaintext credentials.", mistake: "Passwords stored in plaintext or spreadsheets.", evidence_required: true, evidence_guidance: "Password storage policy, evidence of hashed password storage." },
  { id: "L2-047", control_id: "NIST.IA.006", domain: "Identification & Authentication", question: "Change default passwords and disable default accounts.", good: "All default passwords are changed before deployment. Default accounts are disabled.", mistake: "Default admin/password credentials remain on production systems.", evidence_required: true, evidence_guidance: "Default account audit, system build checklist showing password changes." },
  { id: "L2-048", control_id: "NIST.IA.007", domain: "Identification & Authentication", question: "Enforce password complexity and expiration requirements.", good: "Passwords meet complexity requirements and expire periodically.", mistake: "No password policy or policy allows weak passwords.", evidence_required: true, evidence_guidance: "Password policy GPO or admin console screenshot." },
  { id: "L2-049", control_id: "NIST.IA.008", domain: "Identification & Authentication", question: "Lock accounts after a defined number of failed attempts.", good: "Accounts lock after 3-5 failed attempts for a defined period.", mistake: "No account lockout; unlimited attempts allowed.", evidence_required: true, evidence_guidance: "Account lockout policy configuration." },
  { id: "L2-050", control_id: "NIST.IA.009", domain: "Identification & Authentication", question: "Periodically review and revoke unnecessary accounts.", good: "Account reviews are conducted quarterly. Dormant accounts are disabled.", mistake: "Old employee and vendor accounts remain active indefinitely.", evidence_required: true, evidence_guidance: "User access review reports, terminated account list." },
  { id: "L2-051", control_id: "NIST.IA.010", domain: "Identification & Authentication", question: "Use automated mechanisms to manage authentication.", good: "Identity management systems automate account provisioning and deprovisioning.", mistake: "Account management is entirely manual.", evidence_required: true, evidence_guidance: "Identity management system configuration, automated provisioning rules." },
  { id: "L2-052", control_id: "NIST.IA.011", domain: "Identification & Authentication", question: "Implement authentication for all system access points.", good: "All system interfaces (API, console, SSH) require authentication.", mistake: "Some interfaces or APIs have no authentication.", evidence_required: true, evidence_guidance: "Authentication configuration for all system interfaces." },

  // ── Incident Response (IR) ── 6 controls
  { id: "L2-053", control_id: "NIST.IR.001", domain: "Incident Response", question: "Establish an incident response plan and capability.", good: "Incident response plan is documented, tested, and staff are trained.", mistake: "No plan or plan exists but is never tested.", evidence_required: true, evidence_guidance: "IR plan document, IR team contact list, test/exercise records." },
  { id: "L2-054", control_id: "NIST.IR.002", domain: "Incident Response", question: "Train personnel on their incident response roles and responsibilities.", good: "IR team members receive annual training and participate in exercises.", mistake: "Staff don't know what to do during an incident.", evidence_required: true, evidence_guidance: "IR training records, tabletop exercise documentation." },
  { id: "L2-055", control_id: "NIST.IR.003", domain: "Incident Response", question: "Test and exercise the incident response plan periodically.", good: "IR plan is tested at least annually through tabletop exercises or simulations.", mistake: "Plan is never tested.", evidence_required: true, evidence_guidance: "Exercise after-action reports, lessons learned documentation." },
  { id: "L2-056", control_id: "NIST.IR.004", domain: "Incident Response", question: "Contain incidents to minimize impact and preserve evidence.", good: "Containment procedures are documented and followed to limit damage.", mistake: "No containment strategy; incidents spread unchecked.", evidence_required: true, evidence_guidance: "Containment procedures, incident response runbooks." },
  { id: "L2-057", control_id: "NIST.IR.005", domain: "Incident Response", question: "Report incidents to the appropriate authorities and stakeholders.", good: "Incident reporting procedures include DoD, law enforcement, and affected parties.", mistake: "Incidents are not reported due to fear or lack of process.", evidence_required: true, evidence_guidance: "Incident reporting policy, notification templates." },
  { id: "L2-058", control_id: "NIST.IR.006", domain: "Incident Response", question: "Conduct post-incident analysis and lessons learned.", good: "Every incident includes a post-mortem analysis and process improvement.", mistake: "No post-incident review; same issues recur.", evidence_required: true, evidence_guidance: "Post-incident reports, lessons learned documentation." },

  // ── Maintenance (MA) ── 6 controls
  { id: "L2-059", control_id: "NIST.MA.001", domain: "Maintenance", question: "Perform routine maintenance and repairs on systems.", good: "Maintenance is scheduled, documented, and performed by authorized personnel.", mistake: "Maintenance is reactive with no formal process.", evidence_required: true, evidence_guidance: "Maintenance schedule, maintenance logs, work orders." },
  { id: "L2-060", control_id: "NIST.MA.002", domain: "Maintenance", question: "Control and document maintenance tools and procedures.", good: "Maintenance tools are approved, inventoried, and their use is logged.", mistake: "Any tool can be connected to systems with no approval.", evidence_required: true, evidence_guidance: "Approved tool list, maintenance tool logs." },
  { id: "L2-061", control_id: "NIST.MA.003", domain: "Maintenance", question: "Ensure maintenance personnel have appropriate security clearances.", good: "Vendors and maintenance staff are vetted and escorted when on-site.", mistake: "Maintenance personnel given unrestricted access with no vetting.", evidence_required: true, evidence_guidance: "Vendor access policy, maintenance personnel clearance records." },
  { id: "L2-062", control_id: "NIST.MA.004", domain: "Maintenance", question: "Supervise maintenance activities by non-organization personnel.", good: "External maintenance personnel are escorted and their activities are monitored.", mistake: "Vendors left alone with access to sensitive systems.", evidence_required: true, evidence_guidance: "Escort policy, visitor/maintenance logs." },
  { id: "L2-063", control_id: "NIST.MA.005", domain: "Maintenance", question: "Maintain maintenance records and logs.", good: "All maintenance activities are logged with date, person, and actions taken.", mistake: "No records of what was done or who did it.", evidence_required: true, evidence_guidance: "Maintenance logbook, ticketing system records." },
  { id: "L2-064", control_id: "NIST.MA.006", domain: "Maintenance", question: "Protect systems during maintenance from security compromise.", good: "Systems are isolated or sanitized before maintenance when possible.", mistake: "Maintenance is performed on live systems with no precautions.", evidence_required: true, evidence_guidance: "Maintenance security procedures, data sanitization policy." },

  // ── Media Protection (MP) ── 6 controls
  { id: "L2-065", control_id: "NIST.MP.001", domain: "Media Protection", question: "Sanitize or destroy media before disposal or reuse.", good: "Media disposal follows a documented sanitization process (NIST 800-88).", mistake: "Old media is discarded without sanitization.", evidence_required: true, evidence_guidance: "Media sanitization policy, destruction certificates, degausser logs." },
  { id: "L2-066", control_id: "NIST.MP.002", domain: "Media Protection", question: "Protect media containing CUI from unauthorized access.", good: "Media is stored in locked cabinets or encrypted. Media inventories are maintained.", mistake: "Backup tapes and USB drives left in unsecured areas.", evidence_required: true, evidence_guidance: "Media storage photos, media inventory, encryption status." },
  { id: "L2-067", control_id: "NIST.MP.003", domain: "Media Protection", question: "Control access to media and maintain media inventories.", good: "A media inventory is maintained and access is restricted to authorized personnel.", mistake: "No tracking of media; anyone can check out/remove media.", evidence_required: true, evidence_guidance: "Media inventory spreadsheet, media checkout log." },
  { id: "L2-068", control_id: "NIST.MP.004", domain: "Media Protection", question: "Mark media with appropriate CUI labels and handling instructions.", good: "Media containing CUI is clearly labeled with classification and handling requirements.", mistake: "No labeling; CUI media is indistinguishable from regular media.", evidence_required: true, evidence_guidance: "CUI labeling policy, photos of labeled media." },
  { id: "L2-069", control_id: "NIST.MP.005", domain: "Media Protection", question: "Restrict use of portable media to authorized personnel only.", good: "Only approved personnel can use USB drives and external storage. Device control is enforced.", mistake: "Anyone can plug in any USB drive with no restrictions.", evidence_required: true, evidence_guidance: "Device control policy, endpoint DLP/device control settings." },
  { id: "L2-070", control_id: "NIST.MP.006", domain: "Media Protection", question: "Use cryptographic mechanisms to protect CUI on removable media.", good: "Removable media containing CUI is encrypted (e.g., BitLocker To Go).", mistake: "CUI is stored on unencrypted USB drives.", evidence_required: true, evidence_guidance: "Encryption policy for removable media, BitLocker/encryption status." },

  // ── Personnel Security (PS) ── 8 controls
  { id: "L2-071", control_id: "NIST.PS.001", domain: "Personnel Security", question: "Screen personnel before granting access to systems.", good: "Background checks are conducted and documented before access is granted.", mistake: "No screening process; anyone can get access regardless of background.", evidence_required: true, evidence_guidance: "Background check policy, screening records (redacted)." },
  { id: "L2-072", control_id: "NIST.PS.002", domain: "Personnel Security", question: "Ensure personnel understand their security responsibilities.", good: "Employees sign security acknowledgment forms and receive role-specific guidance.", mistake: "Employees unaware of their security responsibilities.", evidence_required: true, evidence_guidance: "Signed security acknowledgment forms, security handbook." },
  { id: "L2-073", control_id: "NIST.PS.003", domain: "Personnel Security", question: "Terminate system access when personnel are separated or transferred.", good: "Access is revoked within 24 hours of termination or transfer.", mistake: "Terminated employees retain access for days or weeks.", evidence_required: true, evidence_guidance: "Termination checklist, access revocation records." },
  { id: "L2-074", control_id: "NIST.PS.004", domain: "Personnel Security", question: "Periodically review personnel access and revoke unnecessary access.", good: "Quarterly access reviews ensure personnel have only what they need.", mistake: "Access accumulates over time with no review.", evidence_required: true, evidence_guidance: "Access review reports, access certification records." },
  { id: "L2-075", control_id: "NIST.PS.005", domain: "Personnel Security", question: "Ensure personnel with privileged access are properly vetted.", good: "Privileged users undergo enhanced screening and periodic reinvestigation.", mistake: "Same vetting for all users regardless of privilege level.", evidence_required: true, evidence_guidance: "Privileged user screening policy, enhanced background check records." },
  { id: "L2-076", control_id: "NIST.PS.006", domain: "Personnel Security", question: "Notify personnel of changes to security policies and procedures.", good: "Policy changes are communicated to all staff with acknowledgment required.", mistake: "Policies change without notification; staff unaware of new requirements.", evidence_required: true, evidence_guidance: "Policy change notification emails, acknowledgment records." },
  { id: "L2-077", control_id: "NIST.PS.007", domain: "Personnel Security", question: "Maintain personnel security records and documentation.", good: "Security records are maintained in a secure HR system with proper retention.", mistake: "Security records are scattered or missing.", evidence_required: true, evidence_guidance: "Personnel security file inventory, HR system security settings." },
  { id: "L2-078", control_id: "NIST.PS.008", domain: "Personnel Security", question: "Provide security awareness training to all personnel.", good: "Training covers security policies, threats, and individual responsibilities.", mistake: "Training is one-time or never updated.", evidence_required: true, evidence_guidance: "Training curriculum, attendance records, training effectiveness surveys." },

  // ── Physical Protection (PE) ── 6 controls
  { id: "L2-079", control_id: "NIST.PE.001", domain: "Physical Protection", question: "Limit physical access to systems and facilities to authorized individuals.", good: "Access cards, biometrics, or guards control physical entry. Access is logged.", mistake: "Server rooms are unlocked; anyone can walk in.", evidence_required: true, evidence_guidance: "Physical access control policy, badge system configuration, access logs." },
  { id: "L2-080", control_id: "NIST.PE.002", domain: "Physical Protection", question: "Protect systems and equipment from environmental hazards.", good: "Fire suppression, climate control, and UPS systems protect critical infrastructure.", mistake: "No environmental controls; servers in an unconditioned closet.", evidence_required: true, evidence_guidance: "Data center environmental monitoring, fire suppression inspection records." },
  { id: "L2-081", control_id: "NIST.PE.003", domain: "Physical Protection", question: "Control and monitor visitor access to facilities.", good: "Visitors sign in, are escorted, and wear visible badges.", mistake: "No visitor management; anyone can enter.", evidence_required: true, evidence_guidance: "Visitor log, visitor badge policy, reception desk procedures." },
  { id: "L2-082", control_id: "NIST.PE.004", domain: "Physical Protection", question: "Maintain physical access logs and records.", good: "Access logs are retained and reviewed for anomalies.", mistake: "No records of who entered or when.", evidence_required: true, evidence_guidance: "Access log reports, badge reader logs." },
  { id: "L2-083", control_id: "NIST.PE.005", domain: "Physical Protection", question: "Secure physical access to network and communications equipment.", good: "Network equipment is in locked racks/cabinets with restricted access.", mistake: "Switches and routers in unlocked areas accessible to anyone.", evidence_required: true, evidence_guidance: "Network closet photos, equipment access list." },
  { id: "L2-084", control_id: "NIST.PE.006", domain: "Physical Protection", question: "Implement physical security controls for alternate work sites.", good: "Remote workers follow physical security guidelines for home offices.", mistake: "No guidance for securing home offices or remote work locations.", evidence_required: true, evidence_guidance: "Telework policy, remote work security checklist." },

  // ── Risk Assessment (RA) ── 3 controls
  { id: "L2-085", control_id: "NIST.RA.001", domain: "Risk Assessment", question: "Conduct risk assessments to identify and prioritize security risks.", good: "Formal risk assessments are conducted regularly with documented results.", mistake: "No risk assessments are performed.", evidence_required: true, evidence_guidance: "Risk assessment report, risk register, methodology documentation." },
  { id: "L2-086", control_id: "NIST.RA.002", domain: "Risk Assessment", question: "Document risk assessment results and mitigation plans.", good: "Risks are documented with remediation plans, owners, and deadlines.", mistake: "Risks are informally discussed but never documented.", evidence_required: true, evidence_guidance: "Risk treatment plan, risk acceptance documentation." },
  { id: "L2-087", control_id: "NIST.RA.003", domain: "Risk Assessment", question: "Update risk assessments periodically and after significant changes.", good: "Risk assessments are updated annually and after major system changes.", mistake: "Risk assessment is a one-time activity, never updated.", evidence_required: true, evidence_guidance: "Risk assessment update schedule, triggers for reassessment policy." },

  // ── Security Assessment (CA) ── 4 controls
  { id: "L2-088", control_id: "NIST.CA.001", domain: "Security Assessment", question: "Assess security controls to verify they are implemented correctly.", good: "Security controls are tested periodically against documented requirements.", mistake: "No testing is performed; vulnerabilities are unknown.", evidence_required: true, evidence_guidance: "Security assessment reports, control testing results." },
  { id: "L2-089", control_id: "NIST.CA.002", domain: "Security Assessment", question: "Conduct periodic security testing and vulnerability assessments.", good: "Vulnerability scans are run regularly and results are tracked.", mistake: "No vulnerability scanning or penetration testing.", evidence_required: true, evidence_guidance: "Vulnerability scan reports, pentest reports, scan schedule." },
  { id: "L2-090", control_id: "NIST.CA.003", domain: "Security Assessment", question: "Remediate identified vulnerabilities and track remediation.", good: "Vulnerabilities are tracked in a remediation system with SLAs based on severity.", mistake: "Vulnerabilities are identified but not tracked or fixed.", evidence_required: true, evidence_guidance: "Vulnerability tracking system, remediation SLA policy, closed finding reports." },
  { id: "L2-091", control_id: "NIST.CA.004", domain: "Security Assessment", question: "Report security assessment results to appropriate stakeholders.", good: "Assessment results are reported to management with action items.", mistake: "Results are filed away without management review.", evidence_required: true, evidence_guidance: "Assessment result briefings, management sign-off records." },

  // ── System & Communications Protection (SC) ── 16 controls
  { id: "L2-092", control_id: "NIST.SC.001", domain: "System & Communications Protection", question: "Protect communications and data in transit using encryption.", good: "TLS 1.2+ is used for all network communications containing sensitive data.", mistake: "Sensitive data sent in cleartext over the network.", evidence_required: true, evidence_guidance: "TLS configuration, certificate inventory, protocol disablement settings." },
  { id: "L2-093", control_id: "NIST.SC.002", domain: "System & Communications Protection", question: "Protect data at rest using cryptographic mechanisms.", good: "Full-disk encryption and/or file-level encryption is used for CUI at rest.", mistake: "CUI stored on unencrypted hard drives or databases.", evidence_required: true, evidence_guidance: "BitLocker/FileVault status, database encryption settings, encryption policy." },
  { id: "L2-094", control_id: "NIST.SC.003", domain: "System & Communications Protection", question: "Control and manage network traffic to protect CUI.", good: "Firewalls, ACLs, and network segmentation control traffic flows.", mistake: "Flat network with no internal firewalls or segmentation.", evidence_required: true, evidence_guidance: "Firewall rule sets, network segmentation diagram, ACL configuration." },
  { id: "L2-095", control_id: "NIST.SC.004", domain: "System & Communications Protection", question: "Use secure network architectures and boundary protection.", good: "DMZs, firewalls, and secure boundaries protect internal networks from external threats.", mistake: "Internal systems directly connected to the internet with no boundary protection.", evidence_required: true, evidence_guidance: "Network architecture diagram, DMZ configuration, boundary firewall rules." },
  { id: "L2-096", control_id: "NIST.SC.005", domain: "System & Communications Protection", question: "Implement network segmentation to protect CUI.", good: "CUI systems are on separate network segments with controlled access between them.", mistake: "CUI systems on the same network as guest Wi-Fi or IoT devices.", evidence_required: true, evidence_guidance: "VLAN configuration, network segmentation policy, firewall inter-VLAN rules." },
  { id: "L2-097", control_id: "NIST.SC.006", domain: "System & Communications Protection", question: "Use secure protocols for system communications.", good: "SSH, HTTPS, and SFTP are used instead of Telnet, HTTP, or FTP.", mistake: "Legacy protocols (Telnet, FTP) used for sensitive communications.", evidence_required: true, evidence_guidance: "Protocol usage policy, disabled protocol list, secure protocol configuration." },
  { id: "L2-098", control_id: "NIST.SC.007", domain: "System & Communications Protection", question: "Protect systems from denial-of-service attacks.", good: "DoS protection measures (rate limiting, WAF, CDN) are in place for critical services.", mistake: "No DoS protection; single point of failure for critical services.", evidence_required: true, evidence_guidance: "WAF/DDoS protection configuration, rate limiting settings, redundancy plan." },
  { id: "L2-099", control_id: "NIST.SC.008", domain: "System & Communications Protection", question: "Implement secure remote access communications.", good: "VPN with strong encryption and MFA secures all remote access.", mistake: "RDP exposed directly to internet with no VPN or encryption.", evidence_required: true, evidence_guidance: "VPN configuration (IPsec/SSL), remote access encryption settings." },
  { id: "L2-100", control_id: "NIST.SC.009", domain: "System & Communications Protection", question: "Control access to publicly accessible systems.", good: "Public-facing systems are hardened, monitored, and separated from internal networks.", mistake: "Internal application accidentally exposed to the public internet.", evidence_required: true, evidence_guidance: "DMZ server configuration, public-facing system inventory, security scan reports." },
  { id: "L2-101", control_id: "NIST.SC.010", domain: "System & Communications Protection", question: "Protect the confidentiality and integrity of transmitted information.", good: "Data integrity checks (checksums, digital signatures) protect against tampering.", mistake: "No integrity checks on data transmissions.", evidence_required: true, evidence_guidance: "Digital signature policy, integrity check configuration, TLS/HMAC settings." },
  { id: "L2-102", control_id: "NIST.SC.011", domain: "System & Communications Protection", question: "Use cryptographic key management practices.", good: "Keys are generated, stored, rotated, and retired following NIST standards.", mistake: "Hardcoded keys in code/configs. Keys never rotated.", evidence_required: true, evidence_guidance: "Key management policy, key rotation schedule, HSM/KMS configuration." },
  { id: "L2-103", control_id: "NIST.SC.012", domain: "System & Communications Protection", question: "Monitor and control network traffic at the boundary.", good: "IDS/IPS and traffic monitoring at network boundaries detect and block threats.", mistake: "No traffic monitoring at network boundary.", evidence_required: true, evidence_guidance: "IDS/IPS configuration, boundary traffic monitoring dashboard." },
  { id: "L2-104", control_id: "NIST.SC.013", domain: "System & Communications Protection", question: "Implement secure wireless network controls.", good: "WPA3-Enterprise with 802.1X authentication and client isolation.", mistake: "Guest network has access to internal resources.", evidence_required: true, evidence_guidance: "Wireless controller settings, client isolation configuration, 802.1X settings." },
  { id: "L2-105", control_id: "NIST.SC.014", domain: "System & Communications Protection", question: "Protect communications with external entities.", good: "External partner connections use encrypted tunnels, VPNs, or dedicated circuits.", mistake: "Sensitive data shared with partners over unencrypted email.", evidence_required: true, evidence_guidance: "Partner connection architecture, encrypted tunnel configuration." },
  { id: "L2-106", control_id: "NIST.SC.015", domain: "System & Communications Protection", question: "Implement security controls for cloud and external services.", good: "Cloud services are assessed, contracts include security requirements, shared responsibility is documented.", mistake: "Cloud services used with no security assessment or contractual protections.", evidence_required: true, evidence_guidance: "Cloud service provider assessment, FedRAMP status, shared responsibility matrix." },
  { id: "L2-107", control_id: "NIST.SC.016", domain: "System & Communications Protection", question: "Protect system and communications integrity.", good: "System integrity is monitored with file integrity monitoring and change detection.", mistake: "No integrity monitoring; system tampering goes undetected.", evidence_required: true, evidence_guidance: "File integrity monitoring (FIM) configuration, change detection alerts." },

  // ── System & Information Integrity (SI) ── 7 controls
  { id: "L2-108", control_id: "NIST.SI.001", domain: "System & Information Integrity", question: "Protect systems from malicious code and unauthorized software.", good: "Antivirus/antimalware is deployed with regular signature updates and scheduled scans.", mistake: "No antivirus. No integrity checks.", evidence_required: true, evidence_guidance: "Antivirus console, scan schedule, malware detection reports." },
  { id: "L2-109", control_id: "NIST.SI.002", domain: "System & Information Integrity", question: "Monitor systems for security anomalies and suspicious activity.", good: "IDS/IPS and behavioral monitoring detect anomalous activity.", mistake: "No monitoring for anomalies or suspicious behavior.", evidence_required: true, evidence_guidance: "IDS/IPS alerts, anomaly detection rules, SIEM dashboards." },
  { id: "L2-110", control_id: "NIST.SI.003", domain: "System & Information Integrity", question: "Implement controls to detect and prevent unauthorized changes.", good: "File integrity monitoring and change control processes catch unauthorized modifications.", mistake: "No detection of unauthorized system changes.", evidence_required: true, evidence_guidance: "Change detection alerts, FIM configuration, baseline comparison reports." },
  { id: "L2-111", control_id: "NIST.SI.004", domain: "System & Information Integrity", question: "Alert on security events and anomalies.", good: "Automated alerting notifies security staff of potential incidents.", mistake: "Alerts are generated but nobody is notified.", evidence_required: true, evidence_guidance: "Alert configuration, notification distribution list, alert response SLA." },
  { id: "L2-112", control_id: "NIST.SI.005", domain: "System & Information Integrity", question: "Protect system integrity using automated tools.", good: "Automated integrity checking tools verify system files and configurations.", mistake: "Manual integrity checking or no checking at all.", evidence_required: true, evidence_guidance: "Integrity checking tool configuration, automated scan schedule." },
  { id: "L2-113", control_id: "NIST.SI.006", domain: "System & Information Integrity", question: "Implement security controls for mobile code and software.", good: "Mobile code (Java, JavaScript, ActiveX) is restricted and controlled.", mistake: "All mobile code runs unrestricted.", evidence_required: true, evidence_guidance: "Browser security settings, mobile code policy, application control rules." },
  { id: "L2-114", control_id: "NIST.SI.007", domain: "System & Information Integrity", question: "Track and remediate software vulnerabilities.", good: "Vulnerability tracking system with defined SLAs for remediation based on CVSS severity.", mistake: "Known vulnerabilities remain unpatched indefinitely.", evidence_required: true, evidence_guidance: "Vulnerability management dashboard, remediation tracking, patch compliance reports." },
];

export function getAllControls(level: CMMCLevel): Control[] {
  if (level === 1) return LEVEL1_CONTROLS;
  return LEVEL2_CONTROLS;
}

export function getControlById(level: CMMCLevel, id: string): Control | undefined {
  const controls = getAllControls(level);
  return controls.find((c) => c.id === id);
}

export const SCOPE_OPTIONS = [
  { value: "servers", label: "Company servers / file shares" },
  { value: "workstations", label: "Employee workstations / laptops" },
  { value: "m365", label: "Microsoft 365 / SharePoint / Teams" },
  { value: "email", label: "Email (Outlook, Gmail, etc.)" },
  { value: "cloud", label: "Cloud storage (Box, Dropbox, etc.)" },
  { value: "paper", label: "Paper documents / filing cabinets" },
  { value: "mobile", label: "Mobile devices (phones, tablets)" },
  { value: "external", label: "External hard drives / USB drives" },
  { value: "vendors", label: "Third-party vendors / contractors" },
];
